/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AttendanceEmployee;

import static AttendanceEmployee.panelEmp.showTable;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author ariel
 */
public class panelEditemp extends javax.swing.JPanel {

    /**
     * Creates new form panelAddemp
     */
    Connection conn = null;
    ResultSet st = null;
    PreparedStatement ps = null;
    String status;
    
    public panelEditemp() {
        initComponents();
        conn = MyConnection.getConnection();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    void reset(){
        txtSearch.setText("");
        txtFname1.setText("");
        txtLname1.setText("");
        txtDepartment1.setText("");
        txtDesignation1.setText("");
        txtNumber1.setText("");
        r_Active1.setSelected(false);
        r_Inactive1.setSelected(false);
        txtAddress1.setText("");
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFname1 = new javax.swing.JTextField();
        txtLname1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumber1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        r_Active1 = new javax.swing.JRadioButton();
        r_Inactive1 = new javax.swing.JRadioButton();
        txtDepartment1 = new javax.swing.JTextField();
        txtDesignation1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(1200, 730));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Edit Employe");

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel2.setText("Department :");

        txtFname1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtFname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFname1ActionPerformed(evt);
            }
        });

        txtLname1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtLname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLname1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel3.setText("Last name :");

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel4.setText("First name :");

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel5.setText(" Designation :");

        txtNumber1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumber1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel6.setText("Status :");

        txtAddress1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel7.setText("Address  :");

        txtSearch.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel8.setText(" Search Id /Username:");

        jLabel9.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel9.setText("Contact No  :");

        btnEdit.setBackground(new java.awt.Color(153, 153, 153));
        btnEdit.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Employe");
        btnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        r_Active1.setBackground(new java.awt.Color(153, 153, 153));
        r_Active1.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        r_Active1.setText("Active");
        r_Active1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_Active1ActionPerformed(evt);
            }
        });

        r_Inactive1.setBackground(new java.awt.Color(153, 153, 153));
        r_Inactive1.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        r_Inactive1.setText("In - Active");
        r_Inactive1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_Inactive1ActionPerformed(evt);
            }
        });

        txtDepartment1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtDepartment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartment1ActionPerformed(evt);
            }
        });

        txtDesignation1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtDesignation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesignation1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(443, 443, 443))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(txtNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addComponent(txtDepartment1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(r_Active1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(r_Inactive1))
                                        .addComponent(txtDesignation1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(txtAddress1)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtLname1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(286, 286, 286))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDesignation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r_Active1)
                            .addComponent(r_Inactive1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname1ActionPerformed

    private void txtLname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLname1ActionPerformed

    private void txtNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumber1ActionPerformed

    private void txtAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress1ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String value1 = txtSearch.getText();
        String value2 = txtFname1.getText();
        String value3 = txtLname1.getText();
        String value4 = txtDepartment1.getText();
        String value5 = txtDesignation1.getText();
        String value6 = txtNumber1.getText();
        String value7 = status;
        String value8 = txtAddress1.getText();
        
        int p = JOptionPane.showConfirmDialog(null, "Are you sure?","Update record", JOptionPane.YES_NO_OPTION);
        if (p == 0){
            try {
                String sql = "UPDATE `emp_list` SET `fname`='"+value2+"',`lname`='"+value3+"',`department`='"+value4+"',`designation`='"+value5+"',`number`='"+value6+"',`status`='"+value7+"',`address`='"+value8+"' WHERE `srno`='"+value1+"' or `fname` like '%" + value1 + "%'";
                ps = conn.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Data updated");
                reset();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        
        showTable();
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void r_Active1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_Active1ActionPerformed
        // TODO add your handling code here:
        status = "Active";
        r_Active1.setSelected(true);
        r_Inactive1.setSelected(false);
    }//GEN-LAST:event_r_Active1ActionPerformed

    private void r_Inactive1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_Inactive1ActionPerformed
        // TODO add your handling code here:
        status = "In - Active";
        r_Active1.setSelected(false);
        r_Inactive1.setSelected(true);
    }//GEN-LAST:event_r_Inactive1ActionPerformed

    private void txtDepartment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartment1ActionPerformed

    private void txtDesignation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesignation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesignation1ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        // TODO add your handling code here:
        if (txtSearch.getText().trim().equals("Enter Employe Id to Search")){
            txtSearch.setText("");
        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        // TODO add your handling code here:
        if (txtSearch.getText().trim().equals("")){
            txtSearch.setText(" Enter Employe Id to Search...");
            txtFname1.setText("");
            txtLname1.setText("");
            txtDepartment1.setText("");
            txtDesignation1.setText("");
            txtNumber1.setText("");
            r_Active1.setSelected(false);
            r_Inactive1.setSelected(false);
            txtAddress1.setText("");
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                String sql = "select * from emp_list where srno = ? or fname like '%" + txtSearch.getText() + "%'";
                ps = conn.prepareStatement(sql);
                ps.setString(1, txtSearch.getText());
                st = ps.executeQuery();
                if (st.next()){
                    txtFname1.setText(st.getString(2));
                    txtLname1.setText(st.getString(3));
                    txtDepartment1.setText(st.getString(4));
                    txtDesignation1.setText(st.getString(5));
                    txtNumber1.setText(st.getString(6));
                    if (st.getString(7).equals("Active")){
                        r_Active1.setSelected(true);
                        r_Inactive1.setSelected(false);
                    } else if (st.getString(7).equals("In - Active")){
                        r_Active1.setSelected(false);
                        r_Inactive1.setSelected(true);
                    }
                    txtAddress1.setText(st.getString(8));
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton r_Active1;
    private javax.swing.JRadioButton r_Inactive1;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtDepartment1;
    private javax.swing.JTextField txtDesignation1;
    private javax.swing.JTextField txtFname1;
    private javax.swing.JTextField txtLname1;
    private javax.swing.JTextField txtNumber1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
