/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AttendanceEmployee;

import static AttendanceEmployee.panelEmp.showTable;
import static AttendanceEmployee.panelAttendance.showTable1;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author ariel
 */
public class panelDeleteemp extends javax.swing.JPanel {

    /**
     * Creates new form panelAddemp
     */
    Connection conn = null;
    ResultSet st = null;
    PreparedStatement ps = null;
    String status;
    
    public panelDeleteemp() {
        initComponents();
        conn = MyConnection.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    void reset(){
        txtSearch1.setText("");
        txtFname2.setText("");
        txtLname2.setText("");
        txtDepartment2.setText("");
        txtDesignation2.setText("");
        txtNumber2.setText("");
        r_Active2.setSelected(false);
        r_Inactive2.setSelected(false);
        txtAddress2.setText("");
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFname2 = new javax.swing.JTextField();
        txtLname2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumber2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSearch1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        r_Active2 = new javax.swing.JRadioButton();
        r_Inactive2 = new javax.swing.JRadioButton();
        txtDepartment2 = new javax.swing.JTextField();
        txtDesignation2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(1200, 730));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Delete Employe");

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel2.setText("Department :");

        txtFname2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtFname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFname2ActionPerformed(evt);
            }
        });

        txtLname2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtLname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLname2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel3.setText("Last name :");

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel4.setText("First name :");

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel5.setText(" Designation :");

        txtNumber2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumber2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel6.setText("Status :");

        txtAddress2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel7.setText("Address  :");

        txtSearch1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtSearch1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearch1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearch1FocusLost(evt);
            }
        });
        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });
        txtSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearch1KeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel8.setText(" Search Id /Username:");

        jLabel9.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel9.setText("Contact No  :");

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Employe");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        r_Active2.setBackground(new java.awt.Color(153, 153, 153));
        r_Active2.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        r_Active2.setText("Active");
        r_Active2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_Active2ActionPerformed(evt);
            }
        });

        r_Inactive2.setBackground(new java.awt.Color(153, 153, 153));
        r_Inactive2.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        r_Inactive2.setText("In - Active");
        r_Inactive2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_Inactive2ActionPerformed(evt);
            }
        });

        txtDepartment2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtDepartment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartment2ActionPerformed(evt);
            }
        });

        txtDesignation2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        txtDesignation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesignation2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(443, 443, 443))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(txtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addComponent(txtDepartment2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(r_Active2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(r_Inactive2))
                                        .addComponent(txtDesignation2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(txtAddress2)
                                .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFname2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtLname2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(286, 286, 286))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDesignation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r_Active2)
                            .addComponent(r_Inactive2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname2ActionPerformed

    private void txtLname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLname2ActionPerformed

    private void txtNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumber2ActionPerformed

    private void txtAddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here
        int p  = JOptionPane.showConfirmDialog(null, "Are you sure?","Delete record", JOptionPane.YES_NO_OPTION);
        if (p == 0 ){
            try {
                String sql = "delete from emp_list where srno = ?";
                ps = conn.prepareStatement(sql);
                ps.setString(1, txtSearch1.getText());
                ps.execute();
                showTable();
                showTable1();
                JOptionPane.showMessageDialog(null, "Data deleted");
                txtSearch1.setText("");
                txtFname2.setText("");
                txtLname2.setText("");
                txtDepartment2.setText("");
                txtDesignation2.setText("");
                txtNumber2.setText("");
                r_Active2.setSelected(false);
                r_Inactive2.setSelected(false);
                txtAddress2.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void r_Active2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_Active2ActionPerformed
        // TODO add your handling code here:
        status = "Active";
        r_Active2.setSelected(true);
        r_Inactive2.setSelected(false);
    }//GEN-LAST:event_r_Active2ActionPerformed

    private void r_Inactive2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_Inactive2ActionPerformed
        // TODO add your handling code here:
        status = "In - Active";
        r_Active2.setSelected(false);
        r_Inactive2.setSelected(true);
    }//GEN-LAST:event_r_Inactive2ActionPerformed

    private void txtDepartment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartment2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartment2ActionPerformed

    private void txtDesignation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesignation2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesignation2ActionPerformed

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void txtSearch1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearch1FocusGained
        // TODO add your handling code here:
        if (txtSearch1.getText().trim().equals("Enter Employe Id to Search")){
            txtSearch1.setText("");
        }
    }//GEN-LAST:event_txtSearch1FocusGained

    private void txtSearch1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearch1FocusLost
        // TODO add your handling code here:
        if (txtSearch1.getText().trim().equals("")){
            txtSearch1.setText(" Enter Employe Id to Search...");
            txtFname2.setText("");
            txtLname2.setText("");
            txtDepartment2.setText("");
            txtDesignation2.setText("");
            txtNumber2.setText("");
            r_Active2.setSelected(false);
            r_Inactive2.setSelected(false);
            txtAddress2.setText("");
        }
    }//GEN-LAST:event_txtSearch1FocusLost

    private void txtSearch1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearch1KeyPressed
        // TODO add your handling code here:
        
       if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           try {
               String sql = "select * from emp_list where srno= ?";
               ps = conn.prepareStatement(sql);
               ps.setString(1, txtSearch1.getText());
               st = ps.executeQuery();
               if(st.next()){
                   txtFname2.setText(st.getString(2));
                    txtLname2.setText(st.getString(3));
                    txtDepartment2.setText(st.getString(4));
                    txtDesignation2.setText(st.getString(5));
                    txtNumber2.setText(st.getString(6));
                    if (st.getString(7).equals("Active")){
                        r_Active2.setSelected(true);
                        r_Inactive2.setSelected(false);
                    } else if (st.getString(7).equals("In - Active")){
                        r_Active2.setSelected(false);
                        r_Inactive2.setSelected(true);
                    }
                    txtAddress2.setText(st.getString(8));
               }
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, ex);
           }
       }
        
    }//GEN-LAST:event_txtSearch1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton r_Active2;
    private javax.swing.JRadioButton r_Inactive2;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtDepartment2;
    private javax.swing.JTextField txtDesignation2;
    private javax.swing.JTextField txtFname2;
    private javax.swing.JTextField txtLname2;
    private javax.swing.JTextField txtNumber2;
    private javax.swing.JTextField txtSearch1;
    // End of variables declaration//GEN-END:variables
}
